// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWIra5bgYBxPsTrBdc3ZI5GJayiW_qdIw',
    appId: '1:656398088309:web:93f9a8cc79bb826de2e03c',
    messagingSenderId: '656398088309',
    projectId: 'en843305-mobile-app-dev-2022',
    authDomain: 'en843305-mobile-app-dev-2022.firebaseapp.com',
    storageBucket: 'en843305-mobile-app-dev-2022.appspot.com',
    measurementId: 'G-SJRVZ7WJ09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLrCMmnYqJj0smiSRKbGOkqPCRny4Q9dA',
    appId: '1:656398088309:android:f04c864b09d67aaee2e03c',
    messagingSenderId: '656398088309',
    projectId: 'en843305-mobile-app-dev-2022',
    storageBucket: 'en843305-mobile-app-dev-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7BdTJ7P5JQRycT80fCr0u0zWoAaH_ko',
    appId: '1:656398088309:ios:cd0f525523aaa93fe2e03c',
    messagingSenderId: '656398088309',
    projectId: 'en843305-mobile-app-dev-2022',
    storageBucket: 'en843305-mobile-app-dev-2022.appspot.com',
    iosClientId:
        '656398088309-5gfgdn05c78f8gcakjug5cfqk424iirg.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApplicationDevelopmentProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ7BdTJ7P5JQRycT80fCr0u0zWoAaH_ko',
    appId: '1:656398088309:ios:cd0f525523aaa93fe2e03c',
    messagingSenderId: '656398088309',
    projectId: 'en843305-mobile-app-dev-2022',
    storageBucket: 'en843305-mobile-app-dev-2022.appspot.com',
    iosClientId:
        '656398088309-5gfgdn05c78f8gcakjug5cfqk424iirg.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApplicationDevelopmentProjects',
  );
}
